/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Empty: typeof import('./../components/common/Empty.vue')['default']
    Loading: typeof import('./../components/common/Loading.vue')['default']
    LyricDisplay: typeof import('./../components/player/LyricDisplay.vue')['default']
    Navbar: typeof import('./../components/layout/Navbar.vue')['default']
    PlayerBar: typeof import('./../components/player/PlayerBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../components/layout/Sidebar.vue')['default']
    Skeleton: typeof import('./../components/common/Skeleton.vue')['default']
  }
}
